version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
# hooks:
#   AfterInstall:
#     - location: npm.sh
#       timeout: 300
#   ApplicationStart:
#     - location: start.sh
#       timeout: 100
