# trigger:
#   branches:
#     include:
#     - main
#     # - testing  



# stages: 
# - template: templates/shared-steps.yml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  #- task: AzureStaticWebApp@0
   # inputs:
    #  azure_static_web_apps_api_token: $(STATIC_WEB_APP_TOKEN)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
     # app_location: "/" # App source code path
      #api_location: "" # Api source code path - optional
      #output_location: "build"
  # - task: AzureStaticWebApp@0
  #   inputs:
  #     workingDirectory: '$(System.DefaultWorkingDirectory)/myapp'
  #     app_location: 'src'
  #     app_build_command: 'npm install && npm run build'
  #     output_location: 'public'
  #     api_location: 'api'
  #     azure_static_web_apps_api_token: 

# - stage: Deploy
#   displayName: Deploy stage
#   jobs:
#   - deployment: VMDeploy
#     displayName: Web deploy
#     environment:
#       name: vikrant
#       resourceType: VirtualMachine
#     strategy:
#       rolling:
#         maxParallel: 2  #for percentages, mention as x%

#         deploy:
#           steps:
#           - download: current
#             artifact: drop

#           - task: Bash@3
#             inputs:
#               targetType: 'inline'
#               script: |
#                   echo "Starting deployment script run"
#                   cd /home/azureuser/green-insight-frontend
#                   sudo rm -rf *
#                   sudo rm -rf .git/
#                   sudo rm -rf .env
#                   sudo rm -rf .gitignore
#                   sudo unzip /home/azureuser/azagent/_work/1/drop/mooglelabs.zip -d /home/azureuser/green-insight-frontend

#                   sudo rm -rf /var/www/html/*
#                   cp -r /home/azureuser/green-insight-frontend/build/* /var/www/html/
