
# Main pipeline
# Extends the shared steps template
# Triggers the pipeline on a push to any branch except master
trigger:
  branches:
    include:
      - master

extends:
  template: templates/shared-steps.yml
  parameters:
    steps:
    - stage: Deploy
      displayName: Deploy stage
      jobs:
      - deployment: VMDeploy
        displayName: Web deploy
        environment:
          name: vikrant
          resourceType: VirtualMachine
        strategy:
          rolling:
            maxParallel: 2  #for percentages, mention as x%

            deploy:
              steps:
              - download: current
                artifact: drop
          
              - task: Bash@3
                inputs:
                  targetType: 'inline'
                  script: |
                # Modify deployment script based on the app type
                    echo "Starting deployment script run"
                    cd /home/azureuser/green-insight-frontend
                    sudo rm -rf *
                    sudo rm -rf .git/
                    sudo rm -rf .env
                    sudo rm -rf .gitignore
                    sudo unzip /home/azureuser/azagent/_work/1/drop/mooglelabs.zip -d /home/azureuser/green-insight-frontend
                
                    sudo rm -rf /var/www/html/*
                    cp -r /home/azureuser/green-insight-frontend/build/* /var/www/html/

