# trigger:
#   branches:
#     include:
#     - main
#     # - testing  



# stages: 
# - template: templates/shared-steps.yml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'src' # App source code path relative to cwd
      api_location: 'api' # Api source code path relative to cwd
      output_location: 'public' # Built app content directory relative to app_location - optional
      cwd: '$(System.DefaultWorkingDirectory)/myapp' # Working directory - optional
      azure_static_web_apps_api_token: "1a904c7517c350dd5b111b9bbe9015462c74280b064bf42aad33968ae872dc063-29d3df3b-4c78-4294-af8b-c8a90e02120500f98802"

# - stage: Deploy
#   displayName: Deploy stage
#   jobs:
#   - deployment: VMDeploy
#     displayName: Web deploy
#     environment:
#       name: vikrant
#       resourceType: VirtualMachine
#     strategy:
#       rolling:
#         maxParallel: 2  #for percentages, mention as x%

#         deploy:
#           steps:
#           - download: current
#             artifact: drop

#           - task: Bash@3
#             inputs:
#               targetType: 'inline'
#               script: |
#                   echo "Starting deployment script run"
#                   cd /home/azureuser/green-insight-frontend
#                   sudo rm -rf *
#                   sudo rm -rf .git/
#                   sudo rm -rf .env
#                   sudo rm -rf .gitignore
#                   sudo unzip /home/azureuser/azagent/_work/1/drop/mooglelabs.zip -d /home/azureuser/green-insight-frontend

#                   sudo rm -rf /var/www/html/*
#                   cp -r /home/azureuser/green-insight-frontend/build/* /var/www/html/
