version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install
      - npm run build
  build:
    commands:
      #- npm start & sleep 60
artifacts:
  files:
    - '**/*'
