trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
# - stage: SONARQUBE 
#   displayName: SONARQUBE 
#   jobs:  
#   - job: Sonarqube
#     displayName: Sonarqube
#     steps:
#     - script: |
#           echo "SONARQUBE SLOT"

- stage: BUILD 
  displayName: BUILD 
  jobs:  
  - job: Build
    displayName: Build
    steps:
    
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Use Node.js'
    
    - script: |
        
        npm install
        npm run build
      displayName: 'Build React app'
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/build'  # Update the path to your build output
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy build to artifact staging directory'
      
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'GS'
        publishLocation: 'Container'

# - stage: TEST 
#   displayName: TEST 
#   jobs:  
#   - job: Test
#     displayName: Test
#     steps:
#     - script: |
#          echo "TEST CASES"


- stage: DEPLOY 
  displayName: DEPLOY 
  jobs:  
  - job: Deploy
    displayName: Deploy
    steps:
    

    - script: |
        ls 
        
        pwd
        cd $(Build.ArtifactStagingDirectory) 
        ls 
    #displayName: 'Build React app'
    
    - task: AzureStaticWebApp@0
      inputs:
        azure_static_web_apps_api_token: $(STATIC_WEB_APP_TOKEN)
        app_location: "/" # App source code path
        api_location: "" # Api source code path - optional
        output_location: "build"  # Set to true if you want to skip build in the pipeline
       
